/**
 * @file guides.h
 * @brief Long-form guides published by the organisation.
 */

#ifndef SITE_GUIDES_H
#define SITE_GUIDES_H

#include "content.h"

static const guide_t g_guides[] = {
    {
        "cwist-getting-started",
        "Building a web service with CWIST",
        "Install the library, serve your first route, add JSON, a database and a "
        "health endpoint, then run the binary you just produced.",
        "CWIST", "Beginner", "12",

        "<h2>What you will build</h2>"
        "<p>A single statically linked binary that answers HTTP on port 8080, "
        "serves one HTML route and one JSON route, reads from an embedded SQLite "
        "database, and exposes metrics and a health check. No runtime is "
        "installed alongside it and no reverse proxy is required for it to "
        "start.</p>"

        "<h2>What you will need</h2>"
        "<ul>"
        "<li>A C compiler with C17 support (GCC or Clang).</li>"
        "<li><code>make</code>, <code>git</code> and about ten minutes.</li>"
        "<li>Linux, macOS or a BSD. CWIST vendors BoringSSL, lsquic, libttak and "
        "SQLite3, so there is no dependency list to satisfy first.</li>"
        "</ul>"

        "<h2>Step 1: install CWIST</h2>"
        "<p>Build from source:</p>"
        "<pre><code class=\"lang-sh\">git clone https://github.com/c4punks/CWIST.git\n"
        "cd CWIST\n"
        "make\n"
        "sudo make install   # optional; PREFIX=/opt/cwist to relocate</code></pre>"
        "<p>Or install the released build through Homebrew, on macOS or "
        "Linuxbrew:</p>"
        "<pre><code class=\"lang-sh\">brew install c4punks/cwist/cwist</code></pre>"
        "<p>Either path gives you <code>libcwist.a</code>, the public headers, "
        "the <code>cwist</code> CLI and <code>cwist.pc</code> pkg-config "
        "metadata.</p>"

        "<h2>Step 2: the smallest server that works</h2>"
        "<p>Create <code>main.c</code>:</p>"
        "<pre><code class=\"lang-c\">#include &lt;cwist/app.h&gt;\n"
        "\n"
        "static void hello(cwist_http_request *req, cwist_http_response *res) {\n"
        "    (void)req;\n"
        "    cwist_sstring_assign(res-&gt;body, \"Hello from CWIST!\");\n"
        "}\n"
        "\n"
        "int main(void) {\n"
        "    cwist_app *app = cwist_app_create();\n"
        "    cwist_app_get(app, \"/\", hello);\n"
        "    cwist_app_listen(app, 8080);\n"
        "    cwist_app_destroy(app);\n"
        "    return 0;\n"
        "}</code></pre>"
        "<p>Three things are worth naming here. <code>cwist_app_create()</code> "
        "allocates the application and everything hanging off it. "
        "<code>cwist_app_get()</code> registers a handler for a method and path. "
        "<code>cwist_app_listen()</code> blocks and runs the accept loop, so "
        "anything you want configured must be configured before it.</p>"

        "<h2>Step 3: compile and run</h2>"
        "<pre><code class=\"lang-sh\">gcc -o server main.c -lcwist -lssl -lcrypto -lz -lzstd \\\n"
        "    -lbrotlienc -lbrotlicommon -luriparser -lcjson -ldl -lpthread -lm\n"
        "./server</code></pre>"
        "<p>If you installed with pkg-config metadata available, "
        "<code>gcc -o server main.c $(pkg-config --cflags --libs cwist)</code> "
        "does the same job. Then, from another terminal:</p>"
        "<pre><code class=\"lang-sh\">curl -i http://localhost:8080/</code></pre>"
        "<p>You should see <code>HTTP/1.1 200 OK</code> and the greeting. If the "
        "connection is refused, the process is not listening yet or port 8080 is "
        "already taken. Change the argument to "
        "<code>cwist_app_listen()</code> and rebuild.</p>"

        "<h2>Step 4: path parameters and query strings</h2>"
        "<p>A route segment beginning with a colon becomes a path parameter, and "
        "both parameter maps are read the same way:</p>"
        "<pre><code class=\"lang-c\">static void greet(cwist_http_request *req, cwist_http_response *res) {\n"
        "    const char *name  = cwist_query_map_get(req-&gt;path_params, \"name\");\n"
        "    const char *style = cwist_query_map_get(req-&gt;query_params, \"style\");\n"
        "\n"
        "    char out[256];\n"
        "    snprintf(out, sizeof(out), \"%s, %s\",\n"
        "             style ? style : \"Hello\", name ? name : \"stranger\");\n"
        "    cwist_sstring_assign(res-&gt;body, out);\n"
        "}\n"
        "\n"
        "cwist_app_get(app, \"/greet/:name\", greet);</code></pre>"
        "<p>Both getters return <code>NULL</code> when the key is absent, so "
        "check before you dereference. <code>/greet/ada?style=Hi</code> now "
        "answers <code>Hi, ada</code>.</p>"

        "<h2>Step 5: answer with JSON</h2>"
        "<p>CWIST links cJSON, so building a response body is ordinary cJSON "
        "work:</p>"
        "<pre><code class=\"lang-c\">#include &lt;cjson/cJSON.h&gt;\n"
        "\n"
        "static void status(cwist_http_request *req, cwist_http_response *res) {\n"
        "    (void)req;\n"
        "    cJSON *doc = cJSON_CreateObject();\n"
        "    cJSON_AddStringToObject(doc, \"service\", \"demo\");\n"
        "    cJSON_AddBoolToObject(doc, \"ready\", 1);\n"
        "\n"
        "    char *text = cJSON_PrintUnformatted(doc);\n"
        "    cwist_http_header_add(&amp;res-&gt;headers, \"Content-Type\",\n"
        "                          \"application/json; charset=utf-8\");\n"
        "    cwist_sstring_assign(res-&gt;body, text);\n"
        "\n"
        "    cJSON_free(text);\n"
        "    cJSON_Delete(doc);\n"
        "}</code></pre>"
        "<p>Note the two frees. <code>cJSON_PrintUnformatted()</code> hands you "
        "an allocation, and the document itself is separate; "
        "<code>cwist_sstring_assign()</code> copies, so both can go once the body "
        "is set.</p>"

        "<h2>Step 6: add a database and the operational endpoints</h2>"
        "<p>Everything below is configuration on the app, and all of it has to "
        "happen before <code>cwist_app_listen()</code>:</p>"
        "<pre><code class=\"lang-c\">int main(void) {\n"
        "    cwist_app *app = cwist_app_create();\n"
        "\n"
        "    cwist_app_use_db(app, \":memory:\");   /* or a file path */\n"
        "    cwist_app_use_pqc_layer(app, true);  /* hybrid PQ TLS */\n"
        "    cwist_app_enable_metrics(app);\n"
        "    cwist_app_enable_healthz(app);\n"
        "    cwist_app_auto_rdbms(app, 5432);     /* local PostgreSQL, if present */\n"
        "\n"
        "    cwist_app_get(app, \"/\", hello);\n"
        "    cwist_app_get(app, \"/status\", status);\n"
        "\n"
        "    cwist_app_listen(app, 8080);\n"
        "    cwist_app_destroy(app);\n"
        "    return 0;\n"
        "}</code></pre>"
        "<p>Use <code>:memory:</code> while you are iterating and a file path "
        "when you want the data to survive a restart. "
        "<code>cwist_app_auto_rdbms()</code> looks for a PostgreSQL, MySQL or "
        "MariaDB on localhost and wires it up if it finds one; if there is "
        "nothing there, the call is a no-op rather than an error.</p>"

        "<h2>Step 7: query the database</h2>"
        "<pre><code class=\"lang-c\">#include &lt;cwist/core/db/sql.h&gt;\n"
        "\n"
        "cwist_db *db = NULL;\n"
        "cwist_db_open(&amp;db, \"app.sqlite\");\n"
        "cwist_db_exec(db, \"CREATE TABLE IF NOT EXISTS notes (\"\n"
        "                  \"id INTEGER PRIMARY KEY, body TEXT)\");\n"
        "\n"
        "cJSON *rows = NULL;\n"
        "cwist_error_t err = cwist_db_query(db, \"SELECT id, body FROM notes\", &amp;rows);\n"
        "if (err.error.err_i16 == 0 &amp;&amp; rows) {\n"
        "    /* rows is a cJSON array of objects keyed by column name */\n"
        "    cJSON_Delete(rows);\n"
        "}</code></pre>"
        "<p>Results come back as a cJSON array, one object per row keyed by "
        "column name, which means the same value can be serialised straight into "
        "a response or walked in C. You own the array; delete it when you are "
        "done.</p>"

        "<h2>Step 8: choose a server mode before you measure</h2>"
        "<p>The reactor is the default and takes the throughput. The classic "
        "thread-per-connection pool answers the median and p99 faster on our "
        "published runs. Switch with an environment variable:</p>"
        "<pre><code class=\"lang-sh\">CWIST_C1M_MODE=0 ./server   # classic thread-per-connection pool\n"
        "./server                    # reactor (default)</code></pre>"
        "<p>Measure both against your own workload before deciding. The separate "
        "guide on server modes explains what each one is optimising and how to "
        "read the distribution.</p>"

        "<h2>Summary</h2>"
        "<p>You have a single binary that routes, speaks JSON, reads a database "
        "and exposes health and metrics, with no runtime deployed beside it. From "
        "here, the WASI guide compiles this same source to wasm32-wasip2, and the "
        "libttak guide covers the memory model underneath.</p>"
    },
    {
        "cwist-server-modes",
        "Choosing between the reactor and the classic pool",
        "Two request paths, two failure shapes. How to tell which one your "
        "workload wants, and how to read the latency distribution honestly.",
        "CWIST", "Intermediate", "8",

        "<h2>The decision in one paragraph</h2>"
        "<p>If the number of open connections is what grows, use the reactor. If "
        "the number of concurrent in-flight requests is bounded and you care "
        "about the median and p99, try the classic pool and measure. That is the "
        "whole heuristic; the rest of this guide is why it holds.</p>"

        "<h2>What the reactor does</h2>"
        "<p>The CWIST reactor is the default mode. It multiplexes many "
        "connections per event loop, so connection count is decoupled from thread "
        "count. A connection costs a reactor slot rather than a parked thread, "
        "which is what makes very high connection counts affordable in memory.</p>"
        "<p>The cost is that requests share a loop. Work queued behind other work "
        "on the same loop waits, and that shows up in the middle of the "
        "distribution rather than at the edges.</p>"

        "<h2>What the classic pool does</h2>"
        "<p>The classic pool is thread-per-connection, enabled with "
        "<code>CWIST_C1M_MODE=0</code>. Every connection gets its own thread, so "
        "no request waits behind another in a batch. In our published runs it "
        "answers the median request in less than half the time of the async "
        "comparison row and stays ahead through p99.</p>"
        "<p>The cost is per-connection memory and scheduler pressure. Thread "
        "count tracks connection count, so this mode stops being the right answer "
        "at the point where connections are cheap and numerous.</p>"

        "<h2>Reading the numbers we publish</h2>"
        "<p>Our benchmark tables report the corrected latency distribution, not "
        "only a mean, because an average hides which requests were slow. Read "
        "them like this:</p>"
        "<ul>"
        "<li><strong>Mean</strong> tells you almost nothing on its own.</li>"
        "<li><strong>P50 through P99</strong> is where the classic pool leads in "
        "our runs.</li>"
        "<li><strong>The extreme tail</strong> is where the crossover happens and "
        "the async comparison is tighter. We say so in the same table rather than "
        "cropping the column.</li>"
        "<li><strong>Memory columns</strong> are end samples, not peaks. Compare "
        "a single-process server against PSS, not RSS.</li>"
        "</ul>"

        "<h2>Why you should not take our numbers</h2>"
        "<p>Published figures come from one commit, one load profile and one CI "
        "environment. The runner CPU model changes between runs and moves the "
        "numbers more than most code changes do. They establish a shape, not a "
        "guarantee, and they are not a causal explanation of scheduling "
        "behaviour.</p>"

        "<h2>Measuring your own</h2>"
        "<pre><code class=\"lang-sh\"># warm up first, and discard the warmup\n"
        "wrk -t4 -c100 -d10s http://localhost:8080/ &gt; /dev/null\n"
        "wrk -t4 -c100 -d10s --latency http://localhost:8080/\n"
        "\n"
        "# then the other mode, same flags, same machine, same commit\n"
        "CWIST_C1M_MODE=0 ./server</code></pre>"
        "<p>Keep the load generator off the machine under test if you can. Run "
        "each mode more than once. If the two runs of the same mode differ by "
        "more than the gap between modes, you have measured your environment "
        "rather than the server.</p>"

        "<h2>Summary</h2>"
        "<p>Neither mode is the better one in general. The reactor decouples "
        "connections from threads; the classic pool refuses to queue requests "
        "behind each other. Pick per workload, switch with one environment "
        "variable, and trust your own distribution over anyone's headline "
        "number.</p>"
    },
    {
        "cwist-wasi",
        "Running CWIST on WASI 0.2",
        "Compile a CWIST server to wasm32-wasip2 and serve it under wasmtime, "
        "with the guest owning its own accept loop.",
        "CWIST", "Intermediate", "10",

        "<h2>What you will build</h2>"
        "<p>The same server source from the getting-started guide, compiled to a "
        "<code>.wasm</code> component and run by wasmtime. The guest owns the "
        "accept loop through <code>wasi:sockets</code>, so this is a real server "
        "inside the sandbox rather than a handler invoked by a host.</p>"

        "<h2>What you will need</h2>"
        "<ul>"
        "<li>The WASI SDK (25.0 or newer), for <code>clang</code> with a "
        "<code>wasm32-wasip2</code> target.</li>"
        "<li>wasmtime 25 or newer.</li>"
        "<li>A CWIST checkout, to build the WASI archive.</li>"
        "</ul>"

        "<h2>Step 1: build the WASI archive</h2>"
        "<p>From the CWIST checkout, produce the wasip2 static library. The "
        "target is named after the artefact it builds:</p>"
        "<pre><code class=\"lang-sh\">make libcwist_wasip2_wasm32-wasip2.a</code></pre>"
        "<p>That leaves <code>libcwist_wasip2_wasm32-wasip2.a</code> in the "
        "repository root. It is an ordinary static archive; you link it the way "
        "you would link any other.</p>"

        "<h2>Step 2: compile your server against it</h2>"
        "<pre><code class=\"lang-sh\">$WASI_SDK/bin/clang \\\n"
        "  --target=wasm32-wasip2 -std=c17 -O2 \\\n"
        "  -D_WASI_EMULATED_GETPID \\\n"
        "  -I$CWIST/include -I$CWIST/lib/cjson \\\n"
        "  -o server.wasm main.c \\\n"
        "  $CWIST/libcwist_wasip2_wasm32-wasip2.a \\\n"
        "  -lwasi-emulated-pthread -lwasi-emulated-getpid \\\n"
        "  -Wl,--gc-sections -Wl,-z,stack-size=1048576</code></pre>"
        "<p>Two flags are load-bearing. The emulated pthread and getpid libraries "
        "stand in for POSIX facilities the sandbox does not provide. The stack "
        "size matters because the default wasm stack is small and a template or "
        "TLS path will overflow it; a megabyte is a safe starting point.</p>"

        "<h2>Step 3: run it</h2>"
        "<pre><code class=\"lang-sh\">wasmtime run -S preview2=y -S tcp=y -S inherit-network=y server.wasm</code></pre>"
        "<p>Each flag grants one capability: preview2 selects the component "
        "model ABI, <code>tcp</code> allows socket use, and "
        "<code>inherit-network</code> lets the guest bind on the host's network. "
        "Without them the process starts and then fails to listen, which is the "
        "sandbox behaving correctly.</p>"
        "<pre><code class=\"lang-sh\">curl -i http://localhost:8080/</code></pre>"

        "<h2>Step 4: what changes inside the sandbox</h2>"
        "<ul>"
        "<li><strong>No filesystem unless you grant one.</strong> Pass "
        "<code>--dir .</code> if you need one; otherwise embed what you need at "
        "build time. This site embeds its templates into the binary for exactly "
        "that reason.</li>"
        "<li><strong>Threads are limited.</strong> Prefer the reactor path; "
        "thread-per-connection has nowhere useful to go here.</li>"
        "<li><strong>Environment variables are not inherited</strong> unless you "
        "pass <code>--env</code>.</li>"
        "<li><strong>Time and randomness are host-provided capabilities</strong> "
        "and can be withheld.</li>"
        "</ul>"

        "<h2>Step 5: serving assets without a filesystem</h2>"
        "<p>CWIST's asset registry keeps content in memory and serves it at a "
        "content-hashed URL, which is what makes the no-filesystem case "
        "practical:</p>"
        "<pre><code class=\"lang-c\">cwist_app_asset_add(app, \"css/app.css\", css, strlen(css),\n"
        "                    \"text/css; charset=utf-8\");\n"
        "\n"
        "const char *url = cwist_app_asset_url(app, \"css/app.css\");\n"
        "/* -&gt; /assets/css/app.&lt;hash&gt;.css, immutable for a year */</code></pre>"
        "<p>Changing the bytes changes the URL, so a cache never serves a stale "
        "copy and an unchanged file keeps its URL across restarts. Register "
        "assets before <code>cwist_app_listen()</code>.</p>"

        "<h2>Summary</h2>"
        "<p>A CWIST server compiles to a WASI 0.2 component with no source "
        "changes, keeps its own accept loop, and runs under a capability list you "
        "control. Anything it needs from the outside world (sockets, "
        "files, environment, clock) is something you granted on the "
        "command line.</p>"
    },
    {
        "libttak-arenas",
        "Deterministic memory with libttak arenas",
        "Replace per-object malloc and free with generational arenas, then add "
        "epoch reclamation for the cross-thread case.",
        "libttak", "Intermediate", "11",

        "<h2>The problem this solves</h2>"
        "<p>A long-running C service that allocates per request will eventually "
        "fragment its heap and contend on its allocator. Both show up as an "
        "unstable tail: most requests are fine, and the slow ones are slow for "
        "reasons that do not appear in a profile taken at a calm moment.</p>"
        "<p>Arenas change the shape of the problem. Instead of freeing each "
        "object where it happens to die, you declare a boundary (a "
        "request, a frame, a batch) and reclaim everything inside it at "
        "once.</p>"

        "<h2>Step 1: set up an arena environment</h2>"
        "<pre><code class=\"lang-c\">#include &lt;ttak/mem/arena_helper.h&gt;\n"
        "\n"
        "ttak_arena_env_config_t cfg;\n"
        "ttak_arena_env_config_init(&amp;cfg);   /* defaults first */\n"
        "\n"
        "ttak_arena_env_t env;\n"
        "if (!ttak_arena_env_init(&amp;env, &amp;cfg)) {\n"
        "    /* allocation failed; nothing to destroy */\n"
        "    return -1;\n"
        "}</code></pre>"
        "<p>The environment owns the backing memory and outlives every "
        "generation taken from it. Initialise the config struct through its "
        "<code>_init</code> function rather than zeroing it yourself, so that "
        "future fields get their intended defaults.</p>"

        "<h2>Step 2: take a generation per unit of work</h2>"
        "<pre><code class=\"lang-c\">ttak_arena_generation_t gen;\n"
        "ttak_arena_generation_begin(&amp;env, &amp;gen, epoch_id);\n"
        "\n"
        "void *header = ttak_arena_generation_claim(&amp;env, &amp;gen, 512);\n"
        "void *body   = ttak_arena_generation_claim(&amp;env, &amp;gen, 8192);\n"
        "\n"
        "/* ... handle the request; nothing here calls free() ... */\n"
        "\n"
        "ttak_arena_generation_retire(&amp;env, &amp;gen);</code></pre>"
        "<p><code>claim()</code> is a bump allocation and returns "
        "<code>NULL</code> when the generation cannot satisfy it, so check it "
        "like any allocator. <code>retire()</code> reclaims everything at once. "
        "Every pointer taken from the generation is dead the instant it returns "
        "That is the contract, and it is also the whole benefit.</p>"

        "<h2>Step 3: know how much room is left</h2>"
        "<pre><code class=\"lang-c\">size_t left = ttak_arena_generation_remaining(&amp;gen);\n"
        "if (left &lt; needed) {\n"
        "    /* retire early, or size the generation up at begin() */\n"
        "}</code></pre>"
        "<p>If you want a generation reused rather than returned, "
        "<code>ttak_arena_generation_reset()</code> rewinds it without giving the "
        "memory back to the environment, which is useful for a loop that processes "
        "many small items.</p>"

        "<h2>Step 4: rotate under steady load</h2>"
        "<p><code>ttak_arena_env_rotate()</code> advances the environment so that "
        "retired generations become reusable. Call it at a natural quiet point "
        "(the end of a batch, a tick boundary) rather than on every "
        "request, since the point is to move cleanup to a moment you chose.</p>"

        "<h2>Step 5: the cross-thread case</h2>"
        "<p>Arenas answer the lifetime question inside one unit of work. When a "
        "structure is read by threads that are still inside it while another "
        "thread retires it, that is epoch reclamation's job instead:</p>"
        "<pre><code class=\"lang-c\">#include &lt;ttak/mem/epoch.h&gt;</code></pre>"
        "<p>A reader enters an epoch, works, and leaves. A writer retires the old "
        "structure, and reclamation happens once no reader can still be holding "
        "it. There is no global pause and no stop-the-world phase; the cost is "
        "that reclamation is deferred rather than immediate.</p>"

        "<h2>Step 6: hand ownership over explicitly</h2>"
        "<p>When memory has to outlive the generation that produced it, libttak's "
        "detachable ownership makes that a deliberate call rather than a comment. "
        "Detaching is visible at the call site, which means a reviewer can "
        "answer \"who frees this?\" by reading the code in front of them.</p>"

        "<h2>Rules of thumb</h2>"
        "<ul>"
        "<li>One generation per unit of work, retired on every path including "
        "the error path.</li>"
        "<li>Never let an arena pointer escape the generation without "
        "detaching it.</li>"
        "<li>Size the generation for the common case and handle the overflow "
        "explicitly; a failed claim is not an exceptional event.</li>"
        "<li>Rotate at a boundary you chose, not on a timer you did not.</li>"
        "</ul>"

        "<h2>Summary</h2>"
        "<p>Generational arenas turn per-object cleanup into a scheduled event, "
        "epoch reclamation covers the readers-while-retiring case, and detachable "
        "ownership keeps handover explicit. Together they are why libttak "
        "describes itself as deterministic rather than merely fast.</p>"
    }
};

static const size_t g_guide_count = sizeof(g_guides) / sizeof(g_guides[0]);

#endif /* SITE_GUIDES_H */
