#!/bin/sh
# Embed binary files (web fonts) into a C header so the WASI build can serve
# them without a filesystem.
# Usage: embed_bin.sh <output-header> <file>...
set -eu

out=$1
shift

{
    printf '/* Generated by tools/embed_bin.sh - do not edit. */\n'
    printf '#ifndef SITE_FONTS_H\n#define SITE_FONTS_H\n\n#include <stddef.h>\n\n'
    for f in "$@"; do
        sym=$(basename "$f" | tr 'a-z.-' 'A-Z__')
        printf 'static const unsigned char BIN_%s[] = {\n' "$sym"
        xxd -i < "$f"
        printf '};\n'
        printf 'static const size_t BIN_%s_LEN = sizeof(BIN_%s);\n\n' "$sym" "$sym"
    done
    printf '#endif /* SITE_FONTS_H */\n'
} > "$out"
