#!/bin/sh
# Embed template files into a C header so the WASI build needs no filesystem.
# Usage: embed.sh <output-header> <file>...
set -eu

out=$1
shift

{
    printf '/* Generated by tools/embed.sh - do not edit. */\n'
    printf '#ifndef SITE_TEMPLATES_H\n#define SITE_TEMPLATES_H\n\n'
    for f in "$@"; do
        sym=$(basename "$f" | tr 'a-z.-' 'A-Z__')
        printf 'static const char TPL_%s[] =\n' "$sym"
        sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/"/' -e 's/$/\\n"/' "$f"
        printf ';\n\n'
    done
    printf '#endif /* SITE_TEMPLATES_H */\n'
} > "$out"
